services:
  lunchmate-backend:
    container_name: lunchmate-backend
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    expose:
      - '3000'
    env_file:
      - .env
    restart: always

  nginx:
    image: nginx:alpine
    container_name: lunchmate-nginx
    restart: always
    depends_on:
      - lunchmate-backend
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf.d/prod.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $!; done;'"
