services:
  lunchmate-backend:
    container_name: lunchmate-backend
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - '3000'
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - lunchmate-net

  nginx:
    container_name: lunchmate-nginx
    image: nginx:1.27-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - lunchmate-backend
    restart: unless-stopped
    networks:
      - lunchmate-net

networks:
  lunchmate-net:
    driver: bridge
